In [1]:
import pandas as pd

# Create dataset from IT asset history

data = {
    "Asset_Age": [4, 3, 2, 1, 5, 2],
    "Repair_Count": [1, 2, 2, 0, 3, 1],
    "Maintenance_Cost": [25000, 20000, 8000, 0, 35000, 5000],
    "Asset_Value": [300000, 55000, 65000, 70000, 120000, 50000],
    "Risk_Level": [
        "High",
        "High",
        "Medium",
        "Low",
        "High",
        "Low"
    ]
}

df = pd.DataFrame(data)

display(df)

   Asset_Age  Repair_Count  Maintenance_Cost  Asset_Value Risk_Level
0          4             1             25000       300000       High
1          3             2             20000        55000       High
2          2             2              8000        65000     Medium
3          1             0                 0        70000        Low
4          5             3             35000       120000       High
5          2             1              5000        50000        Low

In [2]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

df["Risk_Level"] = encoder.fit_transform(df["Risk_Level"])

display(df)

   Asset_Age  Repair_Count  Maintenance_Cost  Asset_Value  Risk_Level
0          4             1             25000       300000           0
1          3             2             20000        55000           0
2          2             2              8000        65000           2
3          1             0                 0        70000           1
4          5             3             35000       120000           0
5          2             1              5000        50000           1

In [3]:
from sklearn.model_selection import train_test_split

# Input features
X = df[
    [
        "Asset_Age",
        "Repair_Count",
        "Maintenance_Cost",
        "Asset_Value"
    ]
]

# Target
y = df["Risk_Level"]


# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (4, 4)
Testing data: (2, 4)

In [4]:
from sklearn.tree import DecisionTreeClassifier

# Create model
model = DecisionTreeClassifier(
    random_state=42
)

# Train model
model.fit(
    X_train,
    y_train
)

print("Model trained successfully!")

Model trained successfully!

In [5]:
new_asset = [[
    4,       # Asset age
    3,       # Repair count
    30000,   # Maintenance cost
    60000    # Asset value
]]

prediction = model.predict(new_asset)

print("Predicted Risk Level:", prediction)

Predicted Risk Level: [0]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [6]:
from sklearn.metrics import accuracy_score, classification_report

# Predict test data
y_pred = model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Model Accuracy:", accuracy)

# Detailed report
print(classification_report(y_test, y_pred))

Model Accuracy: 0.5
              precision    recall  f1-score   support

           0       1.00      0.50      0.67         2
           2       0.00      0.00      0.00         0

    accuracy                           0.50         2
   macro avg       0.50      0.25      0.33         2
weighted avg       1.00      0.50      0.67         2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [7]:
risk_mapping = {
    0: "Low Risk",
    1: "Medium Risk",
    2: "High Risk"
}

prediction = model.predict([[4,3,30000,60000]])

risk = risk_mapping[prediction[0]]

print("Asset Risk Prediction:", risk)

Asset Risk Prediction: Low Risk

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [8]:
import pickle

with open("asset_risk_model.pkl", "wb") as file:
    pickle.dump(model, file)

print("Model saved successfully!")

Model saved successfully!